const fs = require('fs');
const path = require('path');

const GAUNTLETTE_SOURCE = 'gauntlette';
const GSTACK_SOURCE = 'gstack';

function cleanMetadataValue(value) {
  return value.split('|')[0].trim();
}

function parseBranch(content) {
  // Try "Branch: xxx" line (e.g. "Branch: master (plan: bugfixes) | Repo: gauntlette")
  const match = content.match(/Branch:\s*(\S+)/);
  return match ? match[1] : null;
}

function parseRepo(content) {
  const match = content.match(/^Repo:\s*(.+)$/m);
  return match ? cleanMetadataValue(match[1]) : null;
}

function parseGenerator(content) {
  const match = content.match(/^Generated by\s+(.+?)\s+on\s+/m);
  return match ? match[1].trim() : null;
}

function parseFrontmatter(content) {
  const lines = content.split('\n');
  if (lines[0] === '---') {
    const result = {
      status: 'UNKNOWN',
      branch: null,
      phase: null,
      project: null,
      repo: null,
      generator: null,
    };

    for (let i = 1; i < lines.length; i++) {
      if (lines[i] === '---') break;
      const colonIdx = lines[i].indexOf(':');
      if (colonIdx !== -1) {
        const key = lines[i].slice(0, colonIdx).trim();
        const val = lines[i].slice(colonIdx + 1).trim();
        result[key] = val;
      }
    }

    return {
      status: result.status || 'UNKNOWN',
      branch: result.branch || null,
      phase: result.phase || null,
      project: result.project || null,
      repo: result.repo || null,
      generator: result.generator || null,
    };
  }

  // Fallback: detect inline bold metadata (e.g. "**Phase:** /survey", "**Status:** Active")
  const phaseMatch = content.match(/\*\*Phase:\*\*\s*\/?(\S+)/);
  const statusMatch = content.match(/\*\*Status:\*\*\s*(.+)$/m);
  const looseStatusMatch = content.match(/^Status:\s*(.+)$/m);

  const status = statusMatch
    ? cleanMetadataValue(statusMatch[1]).toUpperCase()
    : looseStatusMatch
      ? cleanMetadataValue(looseStatusMatch[1]).toUpperCase()
      : phaseMatch
        ? phaseMatch[1].toUpperCase()
        : 'UNKNOWN';

  return {
    status,
    branch: parseBranch(content),
    phase: phaseMatch ? phaseMatch[1] : null,
    project: null,
    repo: parseRepo(content),
    generator: parseGenerator(content),
  };
}

function parseTitle(content) {
  const match = content.match(/^# (.+)$/m);
  return match ? match[1].trim() : null;
}

function parseVision(content) {
  const match = content.match(/## Vision\s*\n([\s\S]*?)(?=\n##\s|\n###\s|$)/);
  if (!match) return null;
  const text = match[1].trim();
  return text || null;
}

function splitTableRow(line) {
  return line.split('|').map(cell => cell.trim()).filter(cell => cell);
}

function parseReviewTable(content) {
  const lines = content.split('\n');

  // Find the review heading for either gauntlette or gstack docs.
  let tableStart = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].match(/^## Gauntlette Review Report/i) || lines[i].match(/^## GSTACK REVIEW REPORT/i)) {
      tableStart = i;
      break;
    }
  }
  if (tableStart === -1) return [];

  // Find the header row (starts with | Review)
  let headerIdx = -1;
  for (let i = tableStart + 1; i < lines.length && i < tableStart + 10; i++) {
    if (lines[i].match(/^\|\s*Review\s*\|/)) {
      headerIdx = i;
      break;
    }
  }
  if (headerIdx === -1) return [];

  const headerCells = splitTableRow(lines[headerIdx]).map(cell => cell.toLowerCase());
  const indices = {
    review: headerCells.indexOf('review'),
    trigger: headerCells.indexOf('trigger'),
    why: headerCells.indexOf('why'),
    runs: headerCells.indexOf('runs'),
    status: headerCells.indexOf('status'),
    findings: headerCells.indexOf('findings'),
  };

  let dataStart = headerIdx + 1;
  if (dataStart < lines.length && lines[dataStart].match(/^\|[\s-|]+$/)) {
    dataStart++;
  }

  const stages = [];
  for (let i = dataStart; i < lines.length; i++) {
    const line = lines[i];
    if (!line.startsWith('|')) break;
    if (line.match(/^\|[\s-|]+$/)) continue;

    const cells = splitTableRow(line);
    if (cells.length < 4) continue;

    stages.push({
      name: indices.review !== -1 ? (cells[indices.review] || '') : '',
      trigger: indices.trigger !== -1 ? (cells[indices.trigger] || '').replace(/`/g, '') : '',
      why: indices.why !== -1 ? (cells[indices.why] || '') : '',
      runs: indices.runs !== -1 ? (parseInt(cells[indices.runs], 10) || 0) : 0,
      status: indices.status !== -1 ? (cells[indices.status] || '—') : '—',
      findings: indices.findings !== -1 ? (cells[indices.findings] || '—') : '—',
    });
  }

  return stages;
}

// Canonical pipeline stage order and their aliases as frontmatter status values
const PIPELINE_STAGES = [
  { name: 'Survey', aliases: ['SURVEY'] },
  { name: 'Product Review', aliases: ['PRODUCT-REVIEW', 'PRODUCT REVIEW'] },
  { name: 'UX Review', aliases: ['UX-REVIEW', 'UX REVIEW'] },
  { name: 'Architecture', aliases: ['ARCH-REVIEW', 'ARCH REVIEW', 'ARCHITECTURE'] },
  { name: 'Fresh Eyes', aliases: ['FRESH-EYES', 'FRESH EYES'] },
  { name: 'CSO Review', aliases: ['CSO-REVIEW', 'CSO REVIEW'] },
  { name: 'Implementation', aliases: ['IMPLEMENT', 'IMPLEMENTATION'] },
  { name: 'Code Review', aliases: ['CODE-REVIEW', 'CODE REVIEW'] },
  { name: 'QA', aliases: ['QUALITY-CHECK', 'QA'] },
  { name: 'Human Review', aliases: ['HUMAN-REVIEW', 'HUMAN REVIEW'] },
  { name: 'Ship', aliases: ['SHIP-IT', 'SHIP'] },
];

function inferStagesFromStatus(planStatus) {
  if (!planStatus) return [];
  const upper = planStatus.toUpperCase();

  let currentIdx = -1;
  for (let i = 0; i < PIPELINE_STAGES.length; i++) {
    if (PIPELINE_STAGES[i].aliases.includes(upper)) {
      currentIdx = i;
      break;
    }
  }
  if (currentIdx === -1) return [];

  return PIPELINE_STAGES.map((stage, i) => ({
    name: stage.name,
    trigger: '',
    runs: i < currentIdx ? 1 : (i === currentIdx ? 1 : 0),
    status: i < currentIdx ? 'DONE' : (i === currentIdx ? 'DONE' : '—'),
    findings: '—',
    visual: i <= currentIdx ? 'completed' : 'pending',
  }));
}

function parseVerdict(content) {
  const match = content.match(/\*\*VERDICT:\*\*\s*(.+)/);
  return match ? match[1].trim() : null;
}

function classifyStatus(status) {
  if (!status) return 'pending';
  const s = status.toUpperCase();
  if (['DONE', 'PASS', 'SHIPPED', 'SUCCESS'].includes(s)) return 'completed';
  if (s.startsWith('CLEAR') || s.startsWith('CLEAN')) return 'clear';
  if (s.startsWith('SKIPPED')) return 'skipped';
  if (s.includes('ISSUES') || s.includes('FAIL') || s.includes('BLOCK')) return 'issues';
  return 'pending';
}

function inferSourceFromPath(filePath) {
  return filePath.includes(`${path.sep}.gstack${path.sep}`) ? GSTACK_SOURCE : GAUNTLETTE_SOURCE;
}

async function parsePlan(filePath, options = {}) {
  const source = options.source || inferSourceFromPath(filePath);

  try {
    const content = await fs.promises.readFile(filePath, 'utf-8');
    const metadata = parseFrontmatter(content);
    const title = parseTitle(content);
    const vision = parseVision(content);
    const stages = parseReviewTable(content);
    const branch = metadata.branch || parseBranch(content);
    const repo = metadata.repo || parseRepo(content) || path.basename(path.dirname(filePath));
    const generator = metadata.generator || parseGenerator(content);
    const stat = await fs.promises.stat(filePath);

    const nameFromFile = path.basename(filePath, '.md');
    const name = source === GSTACK_SOURCE ? (branch || nameFromFile) : nameFromFile;

    const verdict = parseVerdict(content);
    const readyToImplement = verdict ? /ready to implement/i.test(verdict) : false;

    const isShipped = (metadata.status || '').toUpperCase() === 'SHIPPED';
    let finalStages;
    if (isShipped) {
      finalStages = PIPELINE_STAGES.map(stage => ({
        name: stage.name,
        trigger: '',
        runs: 1,
        status: 'DONE',
        findings: '—',
        visual: 'completed',
      }));
    } else if (stages.length > 0) {
      finalStages = stages.map(stage => ({ ...stage, visual: classifyStatus(stage.status) }));
      if (source === GSTACK_SOURCE) {
        const existingNames = new Set(finalStages.map(s => s.name.toLowerCase()));
        const tail = [
          { name: 'Implementation', visual: readyToImplement ? 'current' : 'pending' },
          { name: 'QA', visual: 'pending' },
          { name: 'Ship', visual: 'pending' },
        ];
        for (const t of tail) {
          if (!existingNames.has(t.name.toLowerCase())) {
            finalStages.push({ name: t.name, trigger: '', runs: 0, status: '—', findings: '—', visual: t.visual });
          }
        }
      }
    } else {
      finalStages = inferStagesFromStatus(metadata.status);
    }

    return {
      source,
      repo,
      name,
      filePath,
      lastModified: stat.mtime.toISOString(),
      status: metadata.status,
      phase: metadata.phase,
      project: metadata.project,
      title: title || name,
      vision: vision ? vision.slice(0, 200) : null,
      branch: branch || null,
      generatedBy: generator || null,
      stages: finalStages,
      error: null,
    };
  } catch (err) {
    const repo = path.basename(path.dirname(filePath));
    const name = path.basename(filePath, '.md');
    return {
      source,
      repo,
      name,
      filePath,
      lastModified: null,
      status: 'ERROR',
      title: name,
      vision: null,
      branch: null,
      generatedBy: null,
      stages: [],
      error: err.message,
    };
  }
}

function mergeStageFiles(stageFiles, repoName, projectName) {
  // Build a set of completed phase aliases from the individual files.
  const completedPhases = new Set();
  let latestModified = null;
  let title = null;
  let vision = null;
  let branch = null;
  let latestFile = null;

  for (const sf of stageFiles) {
    if (sf.phase) {
      completedPhases.add(sf.phase.toUpperCase());
    }
    if (sf.lastModified && (!latestModified || sf.lastModified > latestModified)) {
      latestModified = sf.lastModified;
      latestFile = sf;
    }
    if (!title && sf.title && sf.title !== sf.name) title = sf.title;
    if (!vision && sf.vision) vision = sf.vision;
    if (!branch && sf.branch) branch = sf.branch;
  }

  const hasFileFlags = PIPELINE_STAGES.map(stage => stage.aliases.some(alias => completedPhases.has(alias)));

  let lastCompletedIdx = -1;
  for (let i = hasFileFlags.length - 1; i >= 0; i--) {
    if (hasFileFlags[i]) {
      lastCompletedIdx = i;
      break;
    }
  }

  const stages = PIPELINE_STAGES.map((stage, i) => {
    const hasFile = hasFileFlags[i];
    let visual;
    if (hasFile) {
      visual = 'completed';
    } else if (i < lastCompletedIdx) {
      visual = 'skipped';
    } else {
      visual = 'pending';
    }

    return {
      name: stage.name,
      trigger: '',
      runs: hasFile ? 1 : 0,
      status: hasFile ? 'DONE' : '—',
      findings: '—',
      visual,
    };
  });

  const shipStageIdx = PIPELINE_STAGES.findIndex(stage => stage.aliases.includes('SHIP-IT'));
  const shipHasFile = shipStageIdx !== -1 && hasFileFlags[shipStageIdx];
  const allDone = stages.every(stage => stage.visual === 'completed');
  const overallStatus = (allDone || shipHasFile) ? 'SHIPPED' : 'ACTIVE';

  const surveyFile = stageFiles.find(sf => sf.phase && sf.phase.toUpperCase() === 'SURVEY');
  const displayTitle = (surveyFile && surveyFile.title && surveyFile.title !== surveyFile.name)
    ? surveyFile.title
    : title || projectName;

  return {
    source: GAUNTLETTE_SOURCE,
    repo: repoName,
    name: projectName,
    filePath: latestFile ? latestFile.filePath : stageFiles[0].filePath,
    lastModified: latestModified,
    status: overallStatus,
    phase: null,
    project: projectName,
    title: displayTitle,
    vision,
    branch,
    generatedBy: null,
    stages,
    error: null,
  };
}

function workflowFreshness(plan) {
  if (plan.source === GSTACK_SOURCE) {
    return {
      activeMs: 7 * 24 * 60 * 60 * 1000,
      finalMs: 2 * 24 * 60 * 60 * 1000,
    };
  }

  return {
    activeMs: 8 * 60 * 60 * 1000,
    finalMs: 24 * 60 * 60 * 1000,
  };
}

function isFinalStatus(status) {
  const upper = (status || '').toUpperCase();
  return upper === 'SHIPPED' || upper === 'SUCCESS';
}

function isActiveStatus(status) {
  const upper = (status || '').toUpperCase();
  return ['ACTIVE', 'IN PROGRESS', 'APPROVED', 'DRAFT'].includes(upper);
}

function filterFreshWorkflows(workflows) {
  const now = Date.now();
  return workflows.filter(workflow => {
    const status = (workflow.status || '').toUpperCase();
    const age = workflow.lastModified ? (now - new Date(workflow.lastModified).getTime()) : Infinity;
    const freshness = workflowFreshness(workflow);

    if (status === 'UNKNOWN') return false;
    if (age <= freshness.activeMs) return true;
    if (isFinalStatus(status)) return age <= freshness.finalMs;
    return false;
  });
}

function sortWorkflows(workflows) {
  workflows.sort((a, b) => {
    const aActive = isActiveStatus(a.status);
    const bActive = isActiveStatus(b.status);
    if (aActive && !bActive) return -1;
    if (!aActive && bActive) return 1;
    if (a.lastModified && b.lastModified) return b.lastModified.localeCompare(a.lastModified);
    return 0;
  });

  return workflows;
}

async function readMarkdownFilesRecursive(dirPath) {
  const entries = await fs.promises.readdir(dirPath, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;

    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...await readMarkdownFilesRecursive(fullPath));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith('.md')) {
      files.push(fullPath);
    }
  }

  return files;
}

async function loadAllPlans(gauntletteDir) {
  const resolvedDir = path.resolve(gauntletteDir);

  let repos;
  try {
    repos = await fs.promises.readdir(resolvedDir, { withFileTypes: true });
  } catch (err) {
    if (err.code === 'ENOENT') return { plans: [], error: 'directory_missing' };
    throw err;
  }

  const plans = [];
  for (const repo of repos) {
    if (!repo.isDirectory()) continue;

    const repoDir = path.join(resolvedDir, repo.name);
    let files;
    try {
      files = await fs.promises.readdir(repoDir);
    } catch {
      continue;
    }

    const repoParsed = [];
    for (const file of files) {
      if (!file.endsWith('.md')) continue;
      const filePath = path.join(repoDir, file);
      repoParsed.push(await parsePlan(filePath, { source: GAUNTLETTE_SOURCE }));
    }

    const stageFiles = repoParsed.filter(plan => plan.phase);
    const standaloneFiles = repoParsed.filter(plan => !plan.phase);

    if (stageFiles.length > 0) {
      const byProject = {};
      for (const stageFile of stageFiles) {
        const key = stageFile.project || repo.name;
        if (!byProject[key]) byProject[key] = [];
        byProject[key].push(stageFile);
      }

      for (const [projectName, projectFiles] of Object.entries(byProject)) {
        plans.push(mergeStageFiles(projectFiles, repo.name, projectName));
      }
    }

    for (const standalone of standaloneFiles) {
      plans.push(standalone);
    }
  }

  return {
    plans: sortWorkflows(filterFreshWorkflows(plans)),
    error: null,
  };
}

async function loadAllGstackPlans(gstackProjectsDir) {
  const resolvedDir = path.resolve(gstackProjectsDir);

  let projectDirs;
  try {
    projectDirs = await fs.promises.readdir(resolvedDir, { withFileTypes: true });
  } catch (err) {
    if (err.code === 'ENOENT') return { plans: [], error: null };
    throw err;
  }

  const parsed = [];
  for (const projectDir of projectDirs) {
    if (!projectDir.isDirectory() || projectDir.name.startsWith('.')) continue;

    const fullProjectDir = path.join(resolvedDir, projectDir.name);
    let files = [];
    try {
      files = await readMarkdownFilesRecursive(fullProjectDir);
    } catch {
      continue;
    }

    for (const filePath of files) {
      const plan = await parsePlan(filePath, { source: GSTACK_SOURCE });
      if (plan.error) continue;
      if (plan.stages.length === 0) continue;
      parsed.push(plan);
    }
  }

  const newestByWorkflow = new Map();
  for (const plan of parsed) {
    const key = `${plan.repo}::${plan.branch || plan.name}`;
    const existing = newestByWorkflow.get(key);
    if (!existing || (plan.lastModified && plan.lastModified > existing.lastModified)) {
      newestByWorkflow.set(key, plan);
    }
  }

  return {
    plans: sortWorkflows(filterFreshWorkflows(Array.from(newestByWorkflow.values()))),
    error: null,
  };
}

async function loadAllWorkflows(gauntletteDir, gstackProjectsDir) {
  const [gauntlette, gstack] = await Promise.all([
    loadAllPlans(gauntletteDir),
    loadAllGstackPlans(gstackProjectsDir),
  ]);

  return {
    plans: sortWorkflows([...gauntlette.plans, ...gstack.plans]),
    error: gauntlette.error || gstack.error || null,
  };
}

module.exports = {
  parseFrontmatter,
  parseTitle,
  parseVision,
  parseBranch,
  parseRepo,
  parseGenerator,
  parseVerdict,
  parseReviewTable,
  classifyStatus,
  inferStagesFromStatus,
  mergeStageFiles,
  PIPELINE_STAGES,
  parsePlan,
  loadAllPlans,
  loadAllGstackPlans,
  loadAllWorkflows,
};
